---
     - name: install nginx
       package:
        name: nginx
        state: present
     - name: start the service
       ansible.builtin.service:
         name: nginx
         state: started
     - name: Populate service facts
       ansible.builtin.service_facts:

     - name: restart nginx
       ansible.builtin.service:
         name: nginx
         state: restarted
       become: yes
       when: ansible_facts.services['nginx.service']['state'] == 'running'

     - name: stop nginx
       ansible.builtin.service:
         name: nginx
         state: stopped
       become: yes
       when: ansible_facts.services['nginx.service']['state'] == 'running'

     - name: enable nginx
       ansible.builtin.service:
         name: nginx
         enabled: yes
       become: yes
       when: ansible_facts.services['nginx.service']['status'] == 'disabled'

     - name: disable nginx
       ansible.builtin.service:
         name: nginx
         enabled: no
       become: yes
       when: ansible_facts.services['nginx.service']['status'] == 'enabled'

